olx/olx/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path("", include('products.urls')),
    path("api/", include('products.api.urls')),
]

if settings.DEBUG is True:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

olx/products/api/urls.py
from django.urls import path
from products.api.views import product_list_view

urlpatterns = [
    path("products/", product_list_view, name="product-list")
]

olx/products/urls.py
from django.urls import path
from products.views import productList,productDetails,searchView

app_name = "products"

urlpatterns=[
    path("", productList.as_view(), name = "productlist"),
    path("item/<int:pk>", productDetails.as_view(), name = "details"),
    path("search/", searchView.as_view(), name="search"),
]

olx/products/models.py
from django.db import models
from django.db.models.base import Model
from django.db.models import Q
from django.contrib.auth.backends import ModelBackend, UserModel

class Owner(models.Model):
    name = models.CharField(blank = False, max_length=120,null=False)
    email = models.EmailField(blank = False, null=False)
    rollNo = models.CharField(max_length=9, blank = False, null=False)
    phoneNo = models.CharField(max_length=13)
    rating = models.FloatField(blank = True, default=0.0)
    profilePicture = models.ImageField(blank = True, null = True)
    def __str__(self):
        return self.name

class Product(models.Model):
    name = models.CharField(max_length=120, blank = False, null=False)
    company = models.CharField(max_length=120, blank = True)
    price = models.IntegerField(blank = False, null=False)
    description = models.TextField(blank=True, null=True)
    quantity = models.IntegerField(blank = False, null=False)
    owner = models.ForeignKey(Owner, on_delete=models.CASCADE, related_name="products")
    dateCreated = models.DateTimeField(auto_now_add=True)
    lastModified = models.DateTimeField(auto_now=True)
    sold = models.BooleanField(default = False)
    def __str__(self):
        return self.name

    @property
    def get_images(self):
        images = self.image_set.all()
        return images


class Image(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE,related_name="Images")
    images = models.ImageField(blank=True, null=True, upload_to=f'images')
    def __str__(self):
        return self.images.name

    @property
    def ImageURL(self):
        try:
            url = self.image.url
            if url=='':
                url='images/default.jpeg'
        except:
            url = ''
        return url


class EmailBackend(ModelBackend):
    def authenticate(self, request, username=None, password=None, **kwargs):
        try: #to allow authentication through phone number or any other field, modify the below statement
            user = UserModel.objects.get(Q(username__iexact=username) | Q(email__iexact=username))
        except UserModel.DoesNotExist:
            UserModel().set_password(password)
        except UserModel.MultipleObjectsReturned:
            return UserModel.objects.filter(email=username).order_by('id').first()
        else:
            if user.check_password(password) and self.user_can_authenticate(user):
                return user

    def get_user(self, user_id):
        try:
            user = UserModel.objects.get(pk=user_id)
        except UserModel.DoesNotExist:
            return None

        return user if self.user_can_authenticate(user) else None

olx/products/api/views.py
from rest_framework import status
from rest_framework.decorators import api_view
from rest_framework.relations import method_overridden
from rest_framework.response import Response
from rest_framework.serializers import Serializer

from products.models import Product
from products.api.serializers import ProductSerializer

@api_view(["GET", "POST"])
def product_list_view(request):
    if request.method == "GET":
        products = Product.objects.filter(sold=False)
        serializer_context = {
            'request': request,
        }

        serializer = ProductSerializer(products, many=True, context=serializer_context)
        return Response(serializer.data)
    elif request.method == "POST":
        # To Do: Add serializer for image
        serializer = ProductSerializer(data=request.data)
        if serializer.is_valid():
            serializer.save()
            return Response(serializer.data, status=status.HTTP_201_CREATED)
        else:
            return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)

olx/products/views.py
from django.shortcuts import render
from django.views.generic import ListView,DetailView,TemplateView
from products.models import Product
from django.db.models import Q
# Create your views here.

class productList(ListView):

    model = Product
    template_name = "product_list.html"


class productDetails(DetailView):
    model = Product
    template_name = "product_details.html"
    context_object_name = "prod"


class searchView(ListView):
    model = Product
    template_name = "search_list.html"
    context_object_name = "searchedres"
    def get_queryset(self):
        query = self.request.GET['search']
        return Product.objects.filter(sold=False).filter(Q(name__contains=query)|Q(company__contains=query))

olx/products/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title></title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css" integrity="undefined" crossorigin="anonymous">
</head>
<body>
  <nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container">
        <ul class="nav navbar-nav">
          <li><a class = "navbar-brand bigbrand" href = {% url "products:productlist" %}>CampusOlx</a></li>
        </ul>
        <form class="form-inline my-2 my-lg-0" method="GET" action="{% url "products:search" %}">
           <input type="search" name="search" placeholder="Enter the name of the Product">
           {% csrf_token %}
           <button class="btn btn btn-outline-info my-2 my-lg-0" type="submit"> Search </button>
        </form>
        <!--Auth related Nav not fully completed-->
        <ul class="nav navbar-nav navbar-right">
          {% if user.is_authenticated %}

          {% endif %}

        </ul>
   </div>
  </nav>
  {% block body_block %}
  {% endblock %}
</body>
</html>

olx/products/templates/product_details.html
{% extends "base.html" %}
{% block body_block %}
{% for img in prod.Images.all %}
        {% if prod.Images.all.0.images.url != '' %}
            <img src= "{{ img.images.url }}" />
        {% else %}
            <img src= "/uploads/images/default.jpeg" />
        {% endif %}
{% endfor %}
    <p>{{ prod.price }}</p>
    <p>{{ prod.name }}</p>
    <p>{{ prod.description }}</p>
    <p>{{ prod.lastModified }}</p>
{% endblock %}

olx/products/templates/product_list.html
{% extends "base.html" %}
{% block body_block %}
{% for prod in product_list %}
    <a href = "{% url "products:details" prod.pk %}">
        {% if prod.Images.all.0.images.url != '' %}
            <img src= "{{ prod.Images.all.0.images.url }}" />
        {% else %}
            <img src= "uploads/images/default.jpeg" />
        {% endif %}
        <p>{{ prod.price }}</p>
        <p>{{ prod.name }}</p>
        <p>{{ prod.company }}</p>
        <p>{{ prod.lastModified }}</p>
    </a>
{% endfor %}
{% endblock %}

olx/products/templates/search_list.html
{% extends "base.html" %}
{% block body_block %}
{% for prod in searchedres %}
    <a href = "{% url "products:details" prod.pk %}">
        <img src= "{{ prod.Images.all.0.images.url }}" />
        <p>{{ prod.price }}</p>
        <p>{{ prod.name }}</p>
        <p>{{ prod.company }}</p>
        <p>{{ prod.lastModified }}</p>
    </a>
{% endfor %}
{% endblock %}